tcpclient:
# arm-linux-g++ main.cpp -o tcpserver -I /usr/include/mymuduo -L/usr/lib/ -lmymuduo -lpthread -std=c++11 -Wl,-rpath=/usr/lib/ 
	arm-linux-g++ main.cpp -o tcpclient -I /usr/include/mymuduo/ -L/usr/lib/mymuduo -lmymuduo -lpthread -std=c++11
	
clean:
	rm -f tcpclient