tcpserver:
# arm-linux-g++ main.cpp -o tcpserver -I /usr/include/mymuduo -L/usr/lib/ -lmymuduo -lpthread -std=c++11 -Wl,-rpath=/usr/lib/ 
	arm-linux-g++ main.cpp -o tcpserver -I /home/brian/muduo_lib/ -L/usr/lib -lmymuduo -lpthread -std=c++11

clean:
	rm -f tcpserver